# Generated by Django 4.2.3 on 2023-07-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('Caracteristicas', models.CharField(max_length=500)),
                ('Precio', models.PositiveBigIntegerField()),
                ('descripción', models.CharField(max_length=500)),
            ],
        ),
    ]
