# Generated by Django 4.2.3 on 2023-07-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicycle',
            old_name='descripción',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='bicycle',
            old_name='modelo',
            new_name='Modelo',
        ),
    ]
